---
driver:
  name: vagrant
  vm_hostname: orion.jmorgan.org
  network:
    - ['private_network', { type: 'dhcp' }]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1
  - name: debian-8.1
    run_list: recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[open_directory::default]
    attributes:
