name 'open_directory'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures open_directory'
long_description 'Installs/Configures open_directory'
version '0.1.2'

depends 'sslcerts', '~> 0.4'
depends 'chef-vault', '~> 1.3'
depends 'krb5', '~> 2.0'
depends 'openldap', '~> 2.2'
depends 'setup', '~> 0.5'
